apiVersion: v1
kind: Service
metadata:
  labels:
    app: recipelist-backend
  name: recipelist-backend
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 3000
  selector:
    app: recipelist-backend
status:
  loadBalancer: {}
